# Generated by Django 5.0.14 on 2026-06-28 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in', models.CharField(blank=True, max_length=10, null=True)),
                ('check_out', models.CharField(blank=True, max_length=10, null=True)),
                ('hours', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Holiday', 'Holiday'), ('Week Off', 'Week Off'), ('Comp Off', 'Comp Off')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('employee', 'attendance_date')},
            },
        ),
    ]
